# Generated by Django 2.2.6 on 2020-02-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guitars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('prod_year', models.IntegerField()),
                ('stockrem', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guitars.Gtype')),
            ],
        ),
    ]
