# Generated by Django 2.2.6 on 2020-02-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_guitars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitars',
            name='cost',
            field=models.FloatField(),
        ),
    ]
