# Generated by Django 2.2.6 on 2020-02-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0005_guitars_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitars',
            name='color',
        ),
    ]
