# Generated by Django 2.2.6 on 2020-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0007_guitars_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitars',
            name='model',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guitars',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
