# Generated by Django 2.2.6 on 2020-02-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0009_auto_20200215_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitars',
            name='prod_year',
            field=models.IntegerField(null=True, verbose_name=True),
        ),
    ]
