# Generated by Django 2.2.6 on 2020-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0012_auto_20200215_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitars',
            name='color',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='model',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='prod_year',
            field=models.FloatField(),
        ),
    ]
