# Generated by Django 2.2.6 on 2020-02-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0015_auto_20200215_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitars',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
