# Generated by Django 2.2.6 on 2020-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0017_auto_20200215_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitars',
            name='prod_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
